---
title: "Text Mining"
output: rmarkdown::github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,message=FALSE,cache=TRUE)
```

```{r}
library(tm)
library(tidytext)
library(dplyr)
library(tidyr)
library(tidyverse)


```


```{r}
text<-read_csv("C:/Users/Michael/Desktop/text_v2.csv")
text_df<-data_frame(text=text$diary)

```


```{r}

nwords <- function(string, pseudo=F){
  ifelse( pseudo,
         pattern <- "\\S+",
         pattern <- "[[:alpha:]]+"
  )
  
  str_count(string, pattern)
 }

text$diary<-as.character(text$diary)

text$count<-nwords(text$diary)
```


```{r}
ggplot(text, aes(x = year, y = count, group=year), alpha=0.55) +
  geom_boxplot()


ggplot(text, aes(x = year, y = count, group=year), alpha=0.55) +
  geom_boxplot() +
  facet_grid(.~purchased)
```

```{r}
text_df<-data_frame(text=text$diary)

text_df<-text_df%>%drop_na()

data(stop_words)

ttext<-text_df%>%
  ungroup()%>%
  unnest_tokens(word,text)

ttext_count<-text_df %>%
  unnest_tokens(word, text)%>%
  anti_join(stop_words)%>%
  inner_join(get_sentiments("bing")) %>%
  count(word, sentiment,sort = TRUE)%>%
  ungroup()


ttext_count%>%
  group_by(sentiment) %>%
  top_n(20) %>%
  ungroup() %>%
  mutate(word = reorder(word, n)) %>%
  ggplot(aes(word, n, fill = sentiment)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~sentiment, scales = "free_y") +
  labs(y = "Contribution to sentiment",x = NULL) +
  coord_flip()


ttext_bigrams<-text_df%>%
  unnest_tokens(bigram, text, token = "ngrams", n = 2) %>%
  separate(bigram, c("word1", "word2"), sep = " ") %>%
  filter(!word1 %in% stop_words$word,
         !word2 %in% stop_words$word) %>%
  count(word1, word2, sort = TRUE)

ttext_bigrams

bigrams_united <- ttext_bigrams %>%
    unite(bigrams,word1, word2, sep = " ")%>%
    arrange(desc(n))

bigrams_united

ttext_trigram<-text_df%>%
    unnest_tokens(trigram, text, token = "ngrams", n = 3) %>%
    separate(trigram, c("word1", "word2", "word3"), sep = " ") %>%
    filter(!word1 %in% stop_words$word,
           !word2 %in% stop_words$word,
           !word3 %in% stop_words$word) %>%
    count(word1, word2, word3, sort = TRUE)

ttext_trigram

trigrams_united <- ttext_trigram %>%
    unite(trigrams,word1, word2, word3,sep = " ")%>%
    arrange(desc(n))

trigrams_united
```

